# netlify.toml (Phiên bản cuối cùng)
[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[functions]]
  # Áp dụng cho tất cả các functions
  name = "*"
  node_bundler = "esbuild"
